### ISSUE TITLE
Is typedi works with pydantic?

### ISSUE THREAD

**Issue by ego** [bshishov/typedi#12]

**Comment by bshishov** [comment]
Did a quick test (python 3.8, pydantic 1.10.1)

https://github.com/bshishov/typedi/commit/ccf091a30b2a0947d718f8234c8eff7468bd2a34 

`inspect.signature` and `typing.get_type_hints` works fine with `pydantic.BaseModel` so `typedi` is able to pick up the dependencies, at least in simple cases. Not sure about full-featured support though: pydantic may rely on custom annotations or differences between annotations and actual stored types - need to have a closer look

**Comment by bshishov** [comment]
What is your use-case? Can you please provide more elaborate example?

**Comment by ego** [comment]
Thanks for the reply, I see it works.
Very nice, and useful package! Keep supporting it.

And I have one more question about FasApi/Flask/Django, maybe there is exist some example how to integrate `typedi` with popular frameworks?

**Comment by bshishov** [comment]
Thanks. I will provide close-to-real-world examples after stabilzing the API a bit
